app:
  name: bff
  image:
    repository: "onecx/onecx-user-profile-bff"

  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          userProfile:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            delete: permission on all DELETE requests
            adminRead: permission on all admin related GET requests and POST search
            adminWrite: permission on all admin related PUT, POST, PATCH requests, where objects are saved or updated
            adminDelete: permission on all admin related DELETE requests
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-up:all, ocx-pm:read ]
    microservice:
      spec:
        description: OneCX User Profile Backend For Frontend
        name: OneCX User Profile BFF